# Generated by Django 3.1.5 on 2021-02-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zombie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('health', models.IntegerField()),
                ('cur_health', models.IntegerField()),
            ],
        ),
    ]
