# Generated by Django 3.1.5 on 2021-02-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_fighter_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='zombie',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
