# Generated by Django 3.1.5 on 2021-02-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_zombie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='damage',
            field=models.IntegerField(null=True),
        ),
    ]
