# Generated by Django 3.1.5 on 2021-02-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_fighter_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='skills',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
