# Generated by Django 3.1.5 on 2021-02-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210204_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='weapon',
        ),
        migrations.AddField(
            model_name='fighter',
            name='weapon',
            field=models.BooleanField(default=False),
        ),
    ]
