# Generated by Django 3.1.5 on 2021-02-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210204_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='w_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='weapon',
        ),
        migrations.AddField(
            model_name='fighter',
            name='weapon',
            field=models.ManyToManyField(help_text='Select a weapon for this fighter.', to='index.Weapon'),
        ),
    ]
